# Sveltia CMS configuration

# This is where we configure the CMS repo and its collections and fields
# Sveltia CMS generally follows the Decap CMS configuration spec
# Decap CMS docs: https://decapcms.org/docs/intro/
# Sveltia CMS docs: https://github.com/sveltia/sveltia-cms#features

local_backend: true

# Enter your GitHub repo path and branch (defaults to master)
backend:
  name: github
  repo: dyvenia/site-thescalableway
  branch: main

# The folder used to store uploaded images
media_folder: "assets/images"

# The CMS collections and their fields
collections:

  - name: "home"
    label: "Home Page"
    icon: "home"
    create: false
    extension: "njk"
    format: "frontmatter"
    files:
      - file: "src/pages/index.njk"
        label: "Home"
        name: "home"
        fields:
          - { label: "Hero Title", name: "hero.title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero.subtitle", widget: "markdown" }
          - { label: "Learn More Button Text", name: "hero.button_text", widget: "string" }
          - { label: "Learn More Button Target", name: "hero.button_target", widget: "string" }
          - { label: "Introduction Title", name: "intro.title", widget: "string" }
          - { label: "Introduction Content", name: "intro.content", widget: "markdown" }
          - { label: "Highlight One Title", name: "highlight_one.title", widget: "string" }
          - { label: "Highlight One Subtitle", name: "highlight_one.subtitle", widget: "markdown" }
          - { label: "Highlight Two Title One", name: "highlight_two.title1", widget: "string" }
          - { label: "Highlight Two Title Two", name: "highlight_two.title2", widget: "string" }
          - { label: "Highlight Two Content", name: "highlight_two.content", widget: "markdown" }
          - { label: "5 Foundations Title One", name: "foundations_titles.title1", widget: "string" }
          - { label: "5 Foundations Title Two", name: "foundations_titles.title2", widget: "string" }
          - label: "Foundations Keys"
            name: "foundations_elements" #<- this doesn't seem to work
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "string" }
          - { label: "About Us", name: "about.title", widget: "string" }
          - { label: "About Us", name: "about.content", widget: "markdown" }
          - { label: "Why Us", name: "whyus_intro.title", widget: "string" }
          - { label: "Why Us Intro", name: "whyus_intro.content", widget: "string" }
          - label: "Why Us - Elements"
            name: "whyus_elements"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "string" }
          - { label: "Our Services", name: "our_services.title", widget: "string" }
          - label: "Our Services Items"
            name: "our_services_items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Prefix", name: "prefix", widget: "string" }
              - { label: "Description", name: "description", widget: "markdown" }

  - name: "blog"
    label: "Posts"
    label_singular: "Post"
    folder: "src/posts/2024"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string"}
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"], hint: "Enter tags separated by a comma" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "imprint"
    label: "Imprint"
    icon: "policy"
    extension: "yaml"
    format: "yaml"
    files:
      - file: "src/_data/personal.yaml"
        label: "Site Imprint"
        name: "site"
        fields:
          - { label: "Email", name: "email", widget: "string", hint: "Public company email address i.e. hello@company.com" }
          - { label: "Address", name: "address", widget: "text", hint: "Your company legal address" }

  - name: "team"
    label: "Team"
    icon: "group"
    create: true
    extension: "yaml"
    format: "yaml"
    files:
      - file: "src/_data/team.yaml"
        label: "Team"
        name: "team"
        fields:
            - label: "Admins"
              name: "admin"
              widget: "list"
              fields:
                - { label: "Name", name: "name", widget: "string" }
                - { label: "Profile Picture", name: "image", widget: "image" }
                - { label: "Short Description", name: "description_short", widget: "text" }
                - { label: "Long Description", name: "description_long", widget: "text" }
